export const COLUMN_NAME = {
    Id: 'ID',
    Name: 'Nome',
    Gender: 'Género',
    Role: 'Tipo',
    ProfessionalCategory: 'Categoria Profissional',
    Email: 'Email',
    Birthday: 'Data de Nascimento',
    Usf: 'USF',
    Type: 'Tipo',
    Date: 'Data',
    Time: 'Horas',
    Quantity: 'Quantidade',
    energy_kcal: 'kcal',
    water_g: 'Água (g)',
    protein_g: 'Proteínas (g)',
    fats_g: 'Gorduras (g)',
    carbo_hidrats_g: 'Hid. Carb. (g)',
    fiber_g: 'Fibra (g)',
    colesterol_mg: 'Colesterol (mg)'
};
