export const COLUMN_NAME = {
    Id: 'ID',
    Name: 'Nome',
    Gender: 'Género',
    Role: 'Tipo',
    ProfessionalCategory: 'Categoria Profissional',
    Email: 'Email',
    Birthday: 'Data de Nascimento',
    Usf: 'Instituição',
    Type: 'Tipo',
    Date: 'Data',
    Time: 'Horas',
    Quantity: 'Quantidade',
    energy_kcal: 'kcal',
    water_g: 'Água (g)',
    protein_g: 'Proteínas (g)',
    fats_g: 'Gorduras (g)',
    carbo_hidrats_g: 'Hid. Carb. (g)',
    fiber_g: 'Fibra (g)',
    colesterol_mg: 'Colesterol (mg)',
    SleepTime: 'Hora Deitar',
    WakeUpTime: 'Hora Levantar',
    HasWakeUp: 'Qualidade do Sono',
    Description: 'Descrição',
    TotalHours: 'Total de Horas de Sono',
    StartTime: 'Tempo de Início',
    EndTime: 'Tempo de Fim',
    Duration: 'Duração (min)',
    BurnedCalories: 'Calorias Gastas',
    Met: 'MET',
    Code: 'Código',
    energy_kJ: 'kJ',
    vitA_mg: 'Vit. A (mg)',
    vitD_pg: 'Vit. D (pg)',
    tiamina_mg: 'Tiamina (mg)',
    riboflavina_mg: 'Riboflavina (mg)',
    niacina_mg: 'Niacina (mg)',
    vitB6_mg: 'Vit. B6 (mg)',
    vit_B12_pg: 'Vit. B12 (pg)',
    vitC_mg: 'Vit. C (mg)',
    na_mg: 'Sódio (mg)',
    k_mg: 'Potássio (mg)',
    ca_mg: 'Cálcio (mg)',
    p_mg: 'Fósforo (mg)',
    mg_mg: 'Magnésio (mg)',
    fe_mg: 'Ferro (mg)',
    zn_mg: 'Zinco (mg)'
};
